### ISSUE TITLE
while循环几次后就会退出执行脚本，1]    37595 alarm      php loop_check.php

### ISSUE THREAD

**Issue by songlin51** [walkor/GlobalData#5]
`<?php
require 'vendor/autoload.php';
require_once __DIR__ . '/Autoloader.php';
require_once __DIR__ . '/vendor/GlobalData-master/src/Client.php';
set_time_limit(0);

$host = "127.0.0.1";
$port = 2016;
$dataClient = new \GlobalData\Client('127.0.0.1:2018');

while (1){

    if($dataClient->add("mobvista","xxxx") === false){
        unset($dataClient->mobvista);
        $dataClient->mobvista = "xxxx";
    }
}
?>
`

代码哪里有问题吗？还是GlobalData服务有其他限制

**Comment by songlin51** [comment]
`<?php
require 'vendor/autoload.php';
require_once __DIR__ . '/Autoloader.php';
require_once __DIR__ . '/vendor/GlobalData-master/src/Client.php';
set_time_limit(0);

$host = "127.0.0.1";
$port = 2016;
$dataClient = new \GlobalData\Client('127.0.0.1:2018');


while (1){

    if($dataClient->add("mobvista","xxxx") === false){
        unset($dataClient->mobvista);
        $dataClient->mobvista = "xxxx";
    }
}
?>`

**Comment by walkor** [comment]
我这里测试一切正常，有可能是其它地方有代码运行删除了mobvista导致
